export const FETCH_ALL_NEWS = 'FETCH_ALL_NEWS';
export const FETCH_ALL_NEWS_FAIL = 'FETCH_ALL_NEWS_FAIL';
export const FETCH_ALL_NEWS_SUCCESS = 'FETCH_ALL_NEWS_SUCCESS';

export const FETCH_NEWS_BY_CATEGORY = 'FETCH_NEWS_BY_CATEGORY';
export const FETCH_NEWS_BY_CATEGORY_FAIL = 'FETCH_NEWS_BY_CATEGORY_FAIL';
export const FETCH_NEWS_BY_CATEGORY_SUCCESS = 'FETCH_NEWS_BY_CATEGORY_SUCCESS';

export const SELECT_NEWS_CATEGORY = 'SELECT_NEWS_CATEGORY';

export const LOADING_NEWS = 'LOADING_NEWS';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SEARCH_ALL_NEWS = 'SEARCH_NEWS';
export const SEARCH_NEWS_BY_CATEGORY = 'SEARCH_NEWS_BY_CATEGORY';

export const SELECT_NEWS = 'SELECT_NEWS';
export const ADD_TO_BOOKMARK = 'ADD_TO_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
