export const FETCH_ALL_NEWS = 'FETCH_ALL_NEWS';
export const FETCH_ALL_NEWS_FAIL = 'FETCH_ALL_NEWS_FAIL';
export const FETCH_ALL_NEWS_SUCCESS = 'FETCH_ALL_NEWS_SUCCESS';

export const FETCH_NEWS_BY_CATEGORY = 'FETCH_NEWS_BY_CATEGORY';
export const FETCH_NEWS_BY_CATEGORY_FAIL = 'FETCH_NEWS_BY_CATEGORY_FAIL';
export const FETCH_NEWS_BY_CATEGORY_SUCCESS = 'FETCH_NEWS_BY_CATEGORY_SUCCESS';

export const LOADING_NEWS = 'LOADING_NEWS';
